version: 2.1
jobs:
  Development:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "infra2020"
      - GOOGLE_COMPUTE_ZONE: "us-east1-b"
      - VM_NAME: "nfs-server-desarrollo"
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: 
          name: code testing 
          command: |
            apt-get install -y nodejs
            apt-get install -y npm
            npm -g install acorn
            acorn --silent html/typing.js
      - run: 
          name: development deploy
          command: |
            gcloud --quiet compute scp -r html/ ${VM_NAME}:/var/www/html
  Production:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "infra2020"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - VM_NAME: "nfs-server"
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: 
          name: production deploy
          command: |
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} ${VM_NAME} --project ${GOOGLE_PROJECT_ID} --ssh-flag="-t" --command="cd /var/www/InfraTI && git pull origin master;pwd"
workflows:
  version: 2.1
  build:
    jobs:
      - Development:
          filters:
            branches:
              only: master
      - Manual-Approval:
          type: approval
          requires:
            - Development
      - Production :
          requires:
            - Manual-Approval
          filters:
            branches:
              only: master  
